spring.application.name=gestionactivos

# Perfil activo
spring.profiles.active=dev

# Puerto del servidor
server.port=8080

# Configuraci�n de SQL Server en Azure
spring.datasource.url=jdbc:sqlserver://desarrollosoftwaretoto.database.windows.net:1433;database=pablo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=pablo
spring.datasource.password=D3s4rroll0Softw4ar3@4humadosT0tt02025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuraci�n de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n de seguridad JWT
jwt.secret=${JWT_SECRET:myclaveSecretaParaFirmarJWT123456789}
jwt.expiration=86400000

# Configuraciones espec�ficas para API REST
spring.jackson.serialization.fail-on-empty-beans=falsespring.application.name=gestionactivos
